export enum DetailsTranslations {
  boardNotFound = 'details.boardNotFound',
  columnNotFound = 'details.columnNotFound',
  taskNotFound = 'details.taskNotFound',
  userNotFound = 'details.userNotFound',
  defaultError = 'details.defaultError',
  errorTitle = 'details.errorTitle',
  deleteTask = 'details.deleteTask',
  editTask = 'details.editTask',
  deleteColumn = 'details.deleteColumn',
  createTask = 'details.createTask',
  addColumn = 'addColumn',
  taskTitle = 'taskTitle',
  confirm = 'confirm',
  cancel = 'cancel',
  createColumn = 'createColumn',
  addTask = 'addTask',
  boardTitle = 'boardTitle',
}
